# -*- coding: utf-8 -*-
"""practica1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhW1ve50hMSMZLzzft8DfK73By35lZl7

# Programación para Analisis de datos
## Práctica 1: Introducción a Python I
## Índice:

1. [Ejercicios sobre números](#Ejercicios-sobre-números)
2. [Ejercicios sobre strings](#Ejercicios-sobre-Strings)
3. [Ejercicios sobre listas y diccionarios](#Ejercicios-sobre-listas-y-diccionarios)

<b>Nota:</b>
Esta práctica contiene ejercicios que cubren los diferentes temas vistos en la intrudicción de Python como lenguaje de programación. En las celdas de código, donde vea $<CODIGO>$, debera completar con el código que resuelva lo que se pide. En la mayoria de los ejercicios se debera recurrir a las referencias técnicas para resolver los enunciados. Bajo cada seccion esta el link a las referencias oficiales de python, sin embargo no dude en usar otras fuentes.

<hr>

## Ejercicios sobre números</b>
referencia: https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex

2. Calcule el producto de todos los numeros del 1 a 10
"""

# complete con productos
res = <CODIGO>
print('el producto es: ',res)

"""3. Escriba el codigo para calcular el cuadrado de un numero <i>x</i> y la raiz cuadrada de un número <i>y</i>. Prueba variar el valor de <i>x</i> y de <i>y</i>"""

x = 123
y = 477
cuadrado_de_x = <CODIGO>
raiz_de_y = <CODIGO>
print('El cuadrado de x es: ',cuadrado_de_x)
print('La raiz cuadrada de y es: ',raiz_de_y)

"""4. Convierta el valor del entero $x$ en un número decimal y  el valor de un decimal $y$ en un número entero"""

x = 42
y = 88.0
x_en_decimal = <CODIGO>
y_en_entero = <CODIGO>

print('El tipo de x es:',type(x),', el tipo de dato de y es:',type(y))
print('El tipo de x_en_decimal es:',type(x_en_decimal),', el tipo de dato de y_en_entero es:',type(y_en_entero))

"""5. 

I. Sea $a,b,c$ los factores de un poliniomio de orden 2 ($ax^2+bx+c$). Complete el código para encontrar las raices del polinomio. Encuentra algún problema en su código? Prueba cambiar los valores de $a,b$ y $c$ para testear que su algoritmo funciona. En caso de no funcionar, piense para que valores de los factores no funciona.
"""

a = 2
b = 4
c = -10
raiz_1 = <CODIGO> 
raiz_2 = <CODIGO>
print('La raiz 1 es: ',raiz_1)
print('La raiz 2 es: ',raiz_2)

"""5. II. Escriba un codigo para chequear que los valores de las raices computados anteriormente son correctos (HINT:Piense como puede reemplazarlos en la formula de un polinimio)."""

raiz_1_es_correcta = <CODIGO>
raiz_2_es_correcta = <CODIGO>
print('La raiz 1 es correcta:',raiz_1_es_correcta)
print('La raiz 2 es correcta:',raiz_2_es_correcta)

"""6. Calcule el resto de una divisíon entre 2 enteros $a$ y $b$, sin usar el operador división entera de Python. Prueba diferentes valores de $a$ y $b$. Compare sus respuestas con el operador resto ($a$ % $b$)"""

a = 7
b = 2
resto = <CODIGO>
print('El resto es:',resto)

"""7. Cree que la siguiente igualdad es verdadera o falsa. De no obtener el valor esperado, piense que puede estar fallando. Como lo arreglaria?"""

(0.1 + 0.1 + 0.1 ) == 0.3

"""## Ejercicios sobre Strings
referencia https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str

8. Convierta el siguiente string en minuscula y mayuscula
"""

texto = 'HoLa CoMo EsTaS?'
texto_todo_minuscula = <CODIGO>
texto_todo_en_mayuscula = <CODIGO>
print('El texto en minuscula es: ',texto_todo_minuscula)
print('El texto en mayuscula es:',texto_todo_en_mayuscula)

"""9. Separe el siguiente texto en frases, usando comas como caracter para partir"""

# para definir un string multilinea usamos tres comillas seguidas en vez de una
preambulo = """Nos, los representantes del pueblo de la Nación Argentina, reunidos
 en Congreso General Constituyente por voluntad y elección de las provincias 
 que la componen, en cumplimiento de pactos preexistentes, con el objeto de 
 constituir la unión nacional, afianzar la justicia, consolidar la paz 
 interior, proveer a la defensa común, promover el bienestar general, y 
 asegurar los beneficios de la libertad, para nosotros, para nuestra 
 posteridad, y para todos los hombres del mundo que quieran habitar en el
 suelo argentino: invocando la protección de Dios, fuente de toda razón y
 justicia: ordenamos, decretamos y establecemos esta Constitución, para la
 Nación Argentina."""

texto_separado_por_comas = <CODIGO>
print('El texto separado por comas es:',texto_separado_por_comas)

"""10. Cuente la cantidad de palabras el preambulo"""

cantidad_de_palabras = <CODIGO>
print('La cantidad de palabras son:',cantidad_de_palabras)

"""11. Cree un nuevo string que resulte de reemplazar cada apariación de palabra "de" en el preambulo por dos arrobas"""

nuevo_preambulo = <CODIGO>
print('El preambulo cambiado con arrobas es: ',nuevo_preambulo)

"""## Ejercicios sobre listas y diccionarios
referencias: 
* https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range 
* https://docs.python.org/3/library/stdtypes.html#mapping-types-dict

12. Cree una lista vacia, agregarle 10 valores y muestra por pantalla (usando la función print) el 3 elemento
"""

<CODIGO>

"""13. Obtenga el intervalo de la lista desde la posición 3 hasta la 5 incluida"""

<CODIGO>

"""14. Complete el codigo para saber si un elemento pertenece a la lista"""

lista = [4,'3',3,6,7,4,3,False,'323',3,3,5,6,3]
e = 5
pertenece = <CODIGO>
print('El elemento pertenece a la lista: ',pertenece)

"""15. Complete el codigo para obtener una lista solo con los elementos en las posiciones pares respetando el orden original de la lista. Calcule tambien la cantidad de elementos de esa lista."""

lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
lista_solo_elementos_en_posiciones_pares = <CODIGO> 
print('La lista en posiciones pares es: ',lista_solo_elementos_en_posiciones_pares)

"""16. Imprima por pantalla la posición de la primaria aparición del emento e, la cantidad de veces que aparece. Prueba diferentes valores de $e$. ¿Qué sucede si el valor de $e$ no esta presente en la lista?"""

e = 7
lista = [36, 52, 14, 100, 31, 37, 84, 80, 93, 18, 96, 15, 28, 65, 32, 36, 17, 74, 31, 57, 11, 33, 47,
         42, 11, 30, 7, 22, 47, 75, 52, 65, 84, 52, 68, 30, 7, 9, 59, 75, 28,]
primera_posicion_e = <CODIGO>
print('La primera posicion de',e,' es:',primera_posicion_e)

"""17. Cree un diccionario con alemnos 5 elementos, donde las claves sean DNIs y los significados apellidos"""

dic_dni_apellido = {}
<CODIGO>
print('Diccionario DNI-APELLIDO: ',dic_dni_apellido)

"""18. Cree otro diccionario con la misma información pero donde las claves sean apellidos y los significados DNIs."""

dic_apellido_dni= {}
<CODIGO>
print('Diccionario APELLIDO-DNI: ',dic_apellido_dni)

"""19. Escriba código para chequar si el apellido que viene en la variable apellido pertence o no al diccionario del ejercicio 6. Escriba otro código para saber si pertenece al diccionario del ejercicio 7. Prueba diferentes apellidos para chequear todos los casos (donde esten en uno y no en otro, etc)"""

apellido = 'Perez'
pertenece_dic_dni_apellido = <CODIGO>
pertenece_dic_apellido_dni = <CODIGO>
print('El apellido pertenece al diccionario DNI-APELLIDO',pertenece_dic_dni_apellido)
print('El apellido pertenece al diccionario APELLIDO-DNI',pertenece_dic_apellido_dni)

"""20. Borre algun elemento de los diccionarios y prueba reemplazar algun valor ya definido, ¿Qué pasa con el diccionario?"""

